version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  build-test:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - run: dart format ./ && exit $(git diff | wc -l)
      - run: flutter pub get
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: flutter test --platform chrome
      - run: flutter test --coverage
      - run: genhtml -o coverage coverage/lcov.info
      - store_artifacts:
          path: ./coverage
          destination: /coverage
      - run: dart pub publish --dry-run
  example-cognito:
    docker:
      - image: cimg/node:14.16.0
    environment: 
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npx sls deploy
  pubilsh:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - run: dart pub publish
  

workflows: 
  build-test:
    jobs:
      - example-cognito
      - build-test
