name: Move new issues into Inbox
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs: 
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: 202105 - global
          column: Inbox
          repo-token: ${{ secrets.GH_TOKEN }} 
